### ISSUE TITLE
libfido2 build fails on macOS 12.0

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#450]
Hi,
I get below error when i try to build on macOS 12.0.

libfido2/src/hid_osx.c:398:39: error: 'kIOMasterPortDefault'
is deprecated: first deprecated in macOS 12.0

Is below fix ok ?

#include <Availability.h>
#include <AvailabilityVersions.h>

#if __MAC_OS_X_VERSION_MIN_REQUIRED < __MAC_12_0
#define kIOMainPortDefault kIOMasterPortDefault

And replace kIOMasterPortDefault with kIOMainPortDefault.

Regards
Satish.B
