### ISSUE TITLE
typedef redefinition with different types ('int' vs 'enum clockid_t')

### ISSUE THREAD

**Issue by ntrischi** [Yubico/libfido2#268]
I'm attempting to compile libfido2 from source using the `.actions/build-osx-clang` script. The current version fails to build on with macOS 10.15.7. 

**What version of libfido2 are you using?**
1.6.0
**What operating system are you running?**
macOS 10.15.7
**What application are you using in conjunction with libfido2?**
 OpenSSH 8.4p1
**How does the problem manifest itself?**
 When building on the target system. 
```
libfido2-1.6.0/src/../openbsd-compat/time.h:26:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
typedef int clockid_t;
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/time.h:172:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.
make[2]: *** [src/CMakeFiles/fido2_shared.dir/aes256.c.o] Error 1
make[1]: *** [src/CMakeFiles/fido2_shared.dir/all] Error 2
make: *** [all] Error 2
```
**Is the problem reproducible?**
Yes
**What are the steps that lead to the problem?**
 Building via the stated process
**Does the problem happen with different authenticators?**
N/A

**Comment by martelletto** [comment]
It appears CMake failed to detect `clock_gettime()`. Could you share your `CMakeFiles/CMakeError.log`? A quick workaround is to `export CFLAGS="-DHAVE_CLOCK_GETTIME"` prior to `cmake`, but it would be interesting to find out what happened.

**Comment by ntrischi** [comment]
Apologizes for the late reply. I am unable to include my`CMakeFiles/CMakeError.log`. Your suggestion above worked by adding the following flag to `cmake -DCMAKE_C_FLAGS=" -DHAVE_CLOCK_GETTIME"`.
